name: Update AIS Token & Get Nation & Get ThaiRath
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Get AIS Token & Get Nation & Get Thairath
        timeout-minutes: 5
        run: |
          node get_token.js
          node get_media_url.js
          node get_thairth.js

      - name: Commit token
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add roy_token.json nation_token.json thairath_token.json
          git diff --staged --quiet || git commit -m "Update AIS token & Get Nation & Get Thairath"
          git push
